export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_REAL_CUSTOMERS = "GET_REAL_CUSTOMERS";
export const UPDATE_CUSTOMER = "REMOVE_CUSTOMER";
export const FETCH_USER = "FETCH_USER";
export const GET_VEHICLES = "GET_VEHICLES";
export const GET_SERVICES = "GET_SERVICES";
export const GET_ACTIVE_SERVICES = "GET_ACTIVE_SERVICES";
export const GET_ACTIVE_TO_MESSAGES = "GET_ACTIVE_TO_MESSAGES";
