export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_REAL_CUSTOMERS = "GET_REAL_CUSTOMERS";
export const UPDATE_CUSTOMER = "REMOVE_CUSTOMER";
export const FETCH_USER = "FETCH_USER";
export const GET_VEHICLES = "GET_VEHICLES";
